version: '3.8'

services:
  web-app:
    build:
      context: ./web-app
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE="db"
volumes:
  data: