name: CI/CD Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      MONGO_INITDB_ROOT_USERNAME: ${{secrets.MONGO_INITDB_ROOT_USERNAME}}
      MONGO_INITDB_ROOT_PASSWORD: ${{secrets.MONGO_INITDB_ROOT_PASSWORD}}
      FLASK_SECRET_KEY: ${{secret.FLASK_SECRET_KEY}}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2

    - name: deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SERVER_IP}}
        username: ${{secrets.SERVER_USER}}
        key: ${{secrets.SERVER_KEY}}
        script: |
          cd 5-final-project-ensemble
          git pull
          docker-compose down
          docker-compose up --build -d